In [331]:
import numpy as np

In [332]:
dimension = 5
vocab_size = 8
K = 5


In [333]:
centerWordVec = np.random.uniform(-1, 1, dimension)
centerWordVec 

array([-0.19277778,  0.40293471,  0.96118759,  0.09574369, -0.19438617])

In [334]:
outsideVectors = np.random.uniform(-1, 1, (vocab_size, dimension))
outsideVectors

array([[-0.00465252, -0.84181683,  0.82835072,  0.96323092, -0.35028665],
       [-0.41373002,  0.57167313, -0.10218013,  0.74802833, -0.59345567],
       [ 0.79003104,  0.41784399, -0.88993655,  0.89801779,  0.77627816],
       [ 0.99778389,  0.26310098, -0.7752117 , -0.92064291, -0.79088009],
       [-0.03829698, -0.06714139, -0.81687983, -0.14829662,  0.26541461],
       [-0.63112357, -0.19095941, -0.2926567 ,  0.86031149, -0.96139777],
       [-0.48027176, -0.79696242,  0.53388056,  0.64311424, -0.78993094],
       [-0.07050735,  0.98148102,  0.3560128 , -0.81101499,  0.49240924]])

In [335]:
outsideWordIdx = np.random.randint(0, vocab_size, 1).item()
outsideWordIdx

1

In [336]:
negSampleWordIndices = list(np.random.randint(0, vocab_size, K))
negSampleWordIndices

[1, 4, 6, 6, 6]

In [337]:
indices = [outsideWordIdx] + negSampleWordIndices
indices
indices = [1,2,3,4,5,6]


In [338]:
outsideVectors[indices[0]]

array([-0.41373002,  0.57167313, -0.10218013,  0.74802833, -0.59345567])

In [339]:
outsideVectors[indices[1:]]

array([[ 0.79003104,  0.41784399, -0.88993655,  0.89801779,  0.77627816],
       [ 0.99778389,  0.26310098, -0.7752117 , -0.92064291, -0.79088009],
       [-0.03829698, -0.06714139, -0.81687983, -0.14829662,  0.26541461],
       [-0.63112357, -0.19095941, -0.2926567 ,  0.86031149, -0.96139777],
       [-0.48027176, -0.79696242,  0.53388056,  0.64311424, -0.78993094]])

In [340]:
def sigmoid(x):
    s = 1 / ( 1 + np.exp(-x))
    return s

In [341]:
gradCenterVec = outsideVectors[indices[0]] * \
    (sigmoid( outsideVectors[indices[0]].dot(centerWordVec) ) - 1) + \
    np.sum( outsideVectors[indices[1:]] * \
    (1 - sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1)) ) ) )
gradCenterVec

array([-1.05830474, -1.45402694, -1.18341821, -1.52484837, -0.98612978])

In [342]:
term1 = outsideVectors[indices[0]] * \
    (sigmoid( outsideVectors[indices[0]].dot(centerWordVec) ) - 1)
term1

array([ 0.16614738, -0.22957482,  0.04103391, -0.30039625,  0.23832234])

In [343]:
outsideVectors[indices[2]] * \
    (1 - sigmoid( - outsideVectors[indices[2]].dot(centerWordVec.reshape(centerWordVec.shape[0],1)) ) )

array([ 0.31666953,  0.08350111, -0.24603115, -0.29218707, -0.25100388])

In [344]:
outsideVectors[indices[1:]] * \
    (1 - sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1)) ) )

array([[ 0.22766937,  0.12041334, -0.25645991,  0.25878875,  0.22370609],
       [ 0.31666953,  0.08350111, -0.24603115, -0.29218707, -0.25100388],
       [-0.01130227, -0.01981489, -0.24107903, -0.04376556,  0.07832963],
       [-0.32071702, -0.09703953, -0.14871887,  0.43718306, -0.48855191],
       [-0.29892109, -0.49602932,  0.3322872 ,  0.40027423, -0.49165292]])

In [345]:
np.sum( outsideVectors[indices[1:]] * \
    (1 - sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1)) ) ), axis = 0 )

array([-0.08660149, -0.40896928, -0.56000177,  0.7602934 , -0.92917298])

In [346]:
sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1)))

array([[0.71182225],
       [0.68262714],
       [0.70487821],
       [0.49183166],
       [0.37760011]])

In [347]:
gradOutsideVecs = np.zeros(outsideVectors.shape)

In [348]:
for index in indices[1:]:
    gradOutsideVecs[index] += centerWordVec * (1 - sigmoid( - outsideVectors[index].dot(centerWordVec) ))
gradOutsideVecs[indices[0]] += centerWordVec * ( sigmoid( outsideVectors[indices[0]].dot(centerWordVec) ) - 1)
gradOutsideVecs

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.07741648, -0.16181216, -0.38599761, -0.03844914,  0.07806239],
       [-0.05555427,  0.11611682,  0.27699288,  0.0275912 , -0.05601777],
       [-0.06118244,  0.12788054,  0.30505485,  0.03038645, -0.0616929 ],
       [-0.05689292,  0.11891481,  0.2836674 ,  0.02825605, -0.0573676 ],
       [-0.09796357,  0.20475866,  0.4884451 ,  0.04865391, -0.0987809 ],
       [-0.11998487,  0.25078652,  0.59824304,  0.05959086, -0.12098593],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [349]:
gradOutsideVecs[indices[1:]] += \
    centerWordVec * \
    ( 1 - sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1))) )/2
gradOutsideVecs[indices[0]] = centerWordVec * ( sigmoid( outsideVectors[indices[0]].dot(centerWordVec) ) - 1)
gradOutsideVecs

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.07741648, -0.16181216, -0.38599761, -0.03844914,  0.07806239],
       [-0.0833314 ,  0.17417523,  0.41548932,  0.0413868 , -0.08402666],
       [-0.09177365,  0.19182081,  0.45758228,  0.04557967, -0.09253934],
       [-0.08533938,  0.17837222,  0.4255011 ,  0.04238407, -0.08605139],
       [-0.14694535,  0.30713799,  0.73266765,  0.07298087, -0.14817135],
       [-0.1799773 ,  0.37617978,  0.89736457,  0.08938629, -0.1814789 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [350]:
indices

[1, 2, 3, 4, 5, 6]

In [351]:
 centerWordVec*( 1 - sigmoid( - outsideVectors[indices[1:]].dot(centerWordVec.reshape(centerWordVec.shape[0],1))) )

array([[-0.05555427,  0.11611682,  0.27699288,  0.0275912 , -0.05601777],
       [-0.06118244,  0.12788054,  0.30505485,  0.03038645, -0.0616929 ],
       [-0.05689292,  0.11891481,  0.2836674 ,  0.02825605, -0.0573676 ],
       [-0.09796357,  0.20475866,  0.4884451 ,  0.04865391, -0.0987809 ],
       [-0.11998487,  0.25078652,  0.59824304,  0.05959086, -0.12098593]])

In [352]:
indices = [1,2,3]
gradOutsideVecs = np.zeros(outsideVectors.shape)
gradOutsideVecs[indices] += 1
gradOutsideVecs

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])